- name: Install Nginx
  apt:
    name: nginx

- name: Ensure directory layout
  file:
    path: "{{ nginx_conf_dir }}/{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "conf.d"
    - "sites"
    - "certs"

- name: Generate a snakeoil certificate
  command: openssl req -new -newkey rsa:2048 -days 1 -nodes -x509 -keyout {{ nginx_snakeoil_key }} -out {{ nginx_snakeoil_crt }} -subj /CN=snakeoil
  args:
    creates: "{{ nginx_snakeoil_key }}"

- name: Configure Nginx
  template:
    src: "{{ item }}.j2"
    dest: "{{ nginx_conf_dir }}/{{ item }}"
  with_items:
    - "nginx.conf"
    - "conf.d/cloudfront.conf"
    - "conf.d/log.conf"
    - "conf.d/proxy.conf"
    - "sites/decadegraphy.com.conf"
  notify:
    - "reload nginx"

- name: Check Nginx
  command: nginx -t
  changed_when: False
